interval: "10m"
triggerLoopOnEvent: true
policy: "sync"

# TODO: Do we need this?
#domainFilters:
#  - "project1-dev.devops.coop"

sources:
  - service
  - ingress

  # This is needed for external-dns to create records for Gateway API resources.
  - gateway-httproute
