# Based on:
# https://github.com/opentofu/setup-opentofu
# https://cd.foundation/blog/2024/02/28/how-to-deploy-infrastructure-in-ci-cd-using-opentofu/

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: cluster

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  opentofu:
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:

        # TODO This should be a variable. Do we have to specify this? Commenting it out to test.
        # aws-region: us-east-2

        # TODO This needs to be updated to your actual ARN.
        role-to-assume: arn:aws:iam::999999999999:role/github-actions-dev-tf-Role-REDACTED

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    # TODO verify that this is working
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      id: cache
      with:
        path: |
          .terraform
        key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-

    # TODO: verify that it's using the .opentofu-version file to get the version
    - uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6

    - id: fmt
      run: tofu fmt -recursive -check
      continue-on-error: true
    - id: init
      if: steps.cache.outputs.cache-hit != 'true'
      run: tofu init
    - id: validate
      run: tofu validate -no-color

    # Adding this because module.eks_blueprints_addons.module.aws_efs_csi_driver.helm_release.this[0] requires the AWS CLI.
    # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    # TODO: Pin this to a specific version.
    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install

    - id: plan
      run: tofu plan -no-color -input=false -out=plan.file
      continue-on-error: true
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: github.event_name == 'pull_request'
      env:
        PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - if: github.ref == 'refs/heads/main'
      run: tofu apply -no-color -input=false plan.file
